# Generated by Django 2.0.3 on 2018-03-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.DecimalField(decimal_places=0, max_digits=3)),
                ('classtype', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maxnum', models.DecimalField(decimal_places=0, max_digits=3)),
                ('minnum', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('valid', models.BooleanField()),
                ('socre', models.CharField(max_length=100)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Matchteams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Matches')),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registertime', models.DateTimeField(auto_now=True)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Setevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teammembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=40)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Departments')),
            ],
        ),
        migrations.AddField(
            model_name='teammembers',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Teams'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Users'),
        ),
        migrations.AddField(
            model_name='setevents',
            name='setid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Sets'),
        ),
        migrations.AddField(
            model_name='registrations',
            name='setid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Sets'),
        ),
        migrations.AddField(
            model_name='registrations',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Teams'),
        ),
        migrations.AddField(
            model_name='matchteams',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databases.Teams'),
        ),
    ]
